---
title: "TC_DEA"
author: "CF"
date: "`r Sys.Date()`"
output: html_document
---

# Research Question:
## How do regenerative stormwater conveyance (RSC) potential denitrification rates compare across space (a dry vs. in-stream RSC, upstream vs. downstream, island vs. submerged) and seasons?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear environment:
rm(list=ls())

# Set working directory:
setwd("~/GitHub/Denitrification_Enzyme_Assays/TownCreek/analyses") # for R desktop users
#setwd("/cloud/home/r825761/GitHub/Denitrification_Enzyme_Assays/TownCreek/analyses") # for Posit Cloud users

# Use to set root directory for knitr
knitr::opts_knit$set(root.dir="~/GitHub/Denitrification_Enzyme_Assays/TownCreek/analyses") # for R desktop users
```

```{r code dependencies}
require("ggplot2"):require("tidyr"):require("ggpubr"):require("rstatix"):require("stringr"):require("NSM3")
```

```{r Color-blind-friendly palette}
# From: http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r import data}
# Read in denitrification rates from Town Creek DEA, 2023-01-31 sampling:
# Non-mac users, use relative path. Mac users may be able to use relative or absolute path, depending on repo location.

#denit_rates <- read.csv("~/GitHub/Denitrification_Enzyme_Assays/TownCreek/data/20230131/TownCreek_RSC_DEA_20230131.csv") # absolute path
denit_rates_WINTER <- read.csv("../data/20230131/TownCreek_RSC_DEA_20230131.csv") # relative path

# Read in denitrification rates from Town Creek DEA, 2023-03-29 sampling:
#denit_rates_SPRING <- read.csv("~/GitHub/Denitrification_Enzyme_Assays/TownCreek/data/20230329/TownCreek_RSC_DEA_20230329.csv") # absolute path
denit_rates_SPRING <- read.csv("../data/20230329/TownCreek_RSC_DEA_20230329.csv") # relative path

# Read in denitrification rates from Town Creek DEA, 2023-06-21 sampling:
#denit_rates_SUMMER <- read.csv("~/GitHub/Denitrification_Enzyme_Assays/TownCreek/data/20230621/TownCreek_RSC_DEA_20230621.csv") # absolute path
denit_rates_SUMMER <- read.csv("../data/20230621/TownCreek_RSC_DEA_20230621.csv") # relative path

# Read in denitrification rates from Town Creek DEA, 2023-12-05 sampling:
denit_rates_FALL <- read.csv("../data/20231205/TownCreek_RSC_DEA_20231205.csv")

# Pre-RSC denitrification rates, May 26, 2015:
denit_PRE <- read.delim("../data/PreRSC20150526/2015_TC_DEArate.txt")
denit_PRE$Replicate <- as.factor(denit_PRE$Replicate)
```
```{r YSI data}
# Read in GEOL Spring 2023 YSI data:
#YSI_data <- read.csv("~/GitHub/Denitrification_Enzyme_Assays/TownCreek/data/GEOL_TC_YSI_RdataSpring2023.csv") # absolute path
YSI_data <- read.csv("../data/GEOL_TC_YSI_RdataSpring2023.csv") # relative path

YSI_data <- YSI_data[,-c(19:20)] #Trim extra columns
YSI_data <- YSI_data[-c(27:32),] # For now, get rid of sampling day with no values (22 March 2023)
```
```{r}
# Read in N species concentration data:
#sediment_N <- read.csv("~/GitHub/Denitrification_Enzyme_Assays/TownCreek/data/2023_SPRING_SUM_SoilKClExtracts.csv") # absolute path
sediment_N <- read.csv("../data/2023_SPRING_SUM_SoilKClExtracts.csv") # relative path

# Sediment N, dry mass corrected:
sediment_N_DM <- read.csv("../data/NH4_NOX_per_dryMass.csv")
```


```{r Summer with NO_ACET}
plot.denit_rates_SUMMER <- ggplot(denit_rates_SUMMER, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=Acetylene), size = 3, position = position_jitterdodge()) +
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="SUMMER") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_rates_SUMMER
```

```{r Fall with No-ACET}
plot.denit_rates_FALL <- ggplot(denit_rates_FALL, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=Acetylene), size = 3, position = position_jitterdodge()) +
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="FALL") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_rates_FALL
```



```{r remove NO_ACET}
# Winter:
denit_ACET_WINTER <- dplyr::filter(denit_rates_WINTER, denit_rates_WINTER$Acetylene == "ACET", .preserve = TRUE)

# Spring:
denit_SPRING_ACET <- dplyr::filter(denit_rates_SPRING, denit_rates_SPRING$Acetylene == "ACET", .preserve = TRUE)

# Summer:
denit_SUMMER_ACET <- dplyr::filter(denit_rates_SUMMER, denit_rates_SUMMER$Acetylene == "ACET", .preserve = TRUE)

# Summer:
denit_FALL_ACET <- dplyr::filter(denit_rates_FALL, denit_rates_FALL$Acetylene == "ACET", .preserve = TRUE)
```


```{r plot ACET: Winter}
plot.denit_rates_ACET_WINTER <- ggplot(denit_ACET_WINTER, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=Acetylene), size = 3, position = position_jitterdodge()) +
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="none", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_rates_ACET_WINTER

#ggsave("../figures/denit_v_salt_AcetOnly.tiff", plot=plot.denit_ACET, device="tiff", path=NULL, scale=1, width=10, height=7, dpi=600, limitsize=TRUE, bg="white")

#ggsave("../figures/denit_v_salt_AcetOnly.png", plot=plot.denit_ACET, device="png", path=NULL, scale=1, width=10, height=7, dpi=600, limitsize=TRUE, bg="white")
```


```{r Add combined pool name column for easier plotting}
# Winter:
denit_ACET_WINTER$combined_pool_name <- c("I1 (upstream)", "I1 (upstream)", "I4 (downstream)", "I4 (downstream)", "D4 (upstream)", "D4 (upstream)", "D5 (downstream)", "D5 (downstream)")

# Spring:
denit_SPRING_ACET$combined_pool_name <- c("I1 (upstream)", "I1 (upstream)", "I1 (upstream)", "I1 (upstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "D4 (upstream)", "D4 (upstream)", "D4 (upstream)", "D4 (upstream)", "D5 (downstream)", "D5 (downstream)", "D5 (downstream)", "D5 (downstream)")

# Summer:
denit_SUMMER_ACET$combined_pool_name <- c("I1 (upstream)", "I1 (upstream)", "I1 (upstream)", "I1 (upstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "D4 (upstream)", "D4 (upstream)", "D4 (upstream)", "D4 (upstream)", "D5 (downstream)", "D5 (downstream)", "D5 (downstream)", "D5 (downstream)")

# Fall:
denit_FALL_ACET$combined_pool_name <- c("I1 (upstream)", "I1 (upstream)", "I1 (upstream)", "I1 (upstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "I4 (downstream)", "D4 (upstream)", "D4 (upstream)", "D4 (upstream)", "D4 (upstream)", "D5 (downstream)", "D5 (downstream)", "D5 (downstream)", "D5 (downstream)")
```

```{r Winter all factors}
plot.denit_WINTER_ACET_allFactors <- ggplot(denit_ACET_WINTER, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_WINTER_ACET_allFactors
```

```{r check labelling}
# Use this to check that scale_manuals don't label incorrectly:

plot.denit_ACET_allFactors_SPRING <- ggplot(denit_SPRING_ACET, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  #scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  #scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
 # scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Stuff")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allFactors_SPRING
```

```{r SPRING all factors}
plot.denit_ACET_allFactors_SPRING_2 <- ggplot(denit_SPRING_ACET, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allFactors_SPRING_2
```
## Inset Plots
```{r Inset version of Winter Denit}
plot.denit_ACET_allWINTER_INSET <- ggplot(denit_ACET_WINTER, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 10, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40),axis.title=element_text(size=40,face="bold"),
          axis.text=element_text(size=50),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="none", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = "", title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allWINTER_INSET

#ggsave("../figures/denit_WINTER_INSET.png", plot=plot.denit_ACET_allWINTER_INSET, device="png", path=NULL, scale=1, width=7, height=7, dpi=300, limitsize=TRUE, bg="white")
```

```{r Inset version of Spring Denit}
# Excludes outlier to zoom in:
plot.denit_ACET_allSPRING_INSET <- ggplot(denit_SPRING_ACET[-4,], aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 10, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40),axis.title=element_text(size=40,face="bold"),
          axis.text=element_text(size=50),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="none", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = "", title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allSPRING_INSET

#ggsave("../figures/denit_SPRING_INSET.png", plot=plot.denit_ACET_allSPRING_INSET, device="png", path=NULL, scale=1, width=7, height=7, dpi=300, limitsize=TRUE, bg="white")
```

```{r Inset version of Fall Denit}
# Remove outlier to zoom in:
plot.denit_ACET_allFALL_INSET <- ggplot(denit_FALL_ACET[-2,], aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 10, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40),axis.title=element_text(size=40,face="bold"),
          axis.text=element_text(size=50),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="none", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = "", title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allFALL_INSET

#ggsave("../figures/denit_FALL_INSET.png", plot=plot.denit_ACET_allFALL_INSET, device="png", path=NULL, scale=1, width=7, height=7, dpi=300, limitsize=TRUE, bg="white")
```

```{r}
# Again but with outlier removed:
plot.denit_ACET_allFactors_SPRING_2_No4 <- ggplot(denit_SPRING_ACET[-4,], aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allFactors_SPRING_2_No4
```

```{r SUMMER all factors}
plot.denit_ACET_allFactors_SUMMER <- ggplot(denit_SUMMER_ACET, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allFactors_SUMMER
```

```{r FALL all factors}
plot.denit_ACET_allFactors_FALL <- ggplot(denit_FALL_ACET, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_allFactors_FALL
```

```{r Combine 4 seasons DEA}
#Add season information to the 2 dfs before joining:
denit_ACET_WINTER$Season <- "Winter (31 January 2023)"
denit_SPRING_ACET$Season <- "Spring (29 March 2023)"
denit_SUMMER_ACET$Season <- "Summer (21 June 2023)"
denit_FALL_ACET$Season <- "Fall (5 December 2023)"

# Combine the Winter and Spring (denit_SPRING_ACET) into one df:
denit_combined <- merge(denit_ACET_WINTER, denit_SPRING_ACET, all = T)

# Merge Summer into denit_combined:
denit_combined_wSUMMER <- merge(denit_combined, denit_SUMMER_ACET, all = TRUE)

# Merge Fall into denit_combined:
denit_combined_4Seasons <- merge(denit_combined_wSUMMER, denit_FALL_ACET, all = TRUE)

# Must set levels of Season:
denit_combined$Season <- factor(denit_combined$Season, levels = c("Winter (31 January 2023)", "Spring (29 March 2023)"))

denit_combined_wSUMMER$Season <- factor(denit_combined_wSUMMER$Season, levels = c("Winter (31 January 2023)", "Spring (29 March 2023)", "Summer (21 June 2023)"))

denit_combined_4Seasons$Season <- factor(denit_combined_4Seasons$Season, levels = c("Winter (31 January 2023)", "Spring (29 March 2023)", "Summer (21 June 2023)", "Fall (5 December 2023)"))
```

```{r Combine Pre- and Post-RSC DEAs}
# Select post-RSC columns for better overlap with pre-RSC columns:
post_RSC_4merge <- denit_combined_4Seasons %>% dplyr::select(c("Sample_ID", "Water_column", "Denitrification_rate"))

# Select denit_PRE columns for merging:
denit_PRE_4merge <- denit_PRE %>% dplyr::select(c("IDCode", "Type", "Rate"))

# Rename columns to match post_RSC:
colnames(denit_PRE_4merge) <- colnames(post_RSC_4merge)

# Add restoration pre/post column:
post_RSC_4merge$restoration <- "POST"
denit_PRE_4merge$restoration <- "PRE"

# Combine pre and post:
denit_PRE_POST <- rbind(denit_PRE_4merge, post_RSC_4merge)
```


## DEA Stats

```{r Assumption testing}
# Outliers:
Outliers_DEA <- denit_combined_4Seasons %>%
  group_by(Season) %>%
  identify_outliers(Denitrification_rate)
  # There are extreme outliers. Could run with and without outliers.

# Normality:
# CH4 PPM
denit_combined_4Seasons %>%
  group_by(Season) %>%
  shapiro_test(Denitrification_rate)
  # Not normally distributed

  # QQ plot:
ggqqplot(denit_combined_4Seasons, "Denitrification_rate", facet.by = "Season")
```
```{r Wilcox test: RSC}
# Set factors:
denit_combined_4Seasons$RSC <- as.factor(denit_combined_4Seasons$RSC)

# Wilcox Test, nicer format, can use to verify stats on plot:
DEA_wilcox_RSC<- compare_means(Denitrification_rate~RSC, denit_combined_4Seasons, group.by="Season", method = "wilcox.test", paired = F)

# Turn into data frame:
DEA_wilcox_RSC <- as.data.frame(DEA_wilcox_RSC)

# Export the data frame to a .csv file
#write.csv(CH4_wilcox, file = "../figures/pub/tables/Wilcox_NPvP/CH4_wilcox.csv", row.names = T)
```

```{r Wilcox test: Island vs Submerged}
# Subset to only include Island:
denit_4seasons_Island <- denit_combined_4Seasons %>%
 filter(Water_column == "island")

# Subset to submerged and P4:
denit_submergedP4 <- denit_combined_4Seasons %>%
  filter(Water_column == "submerged" & Pool == "I4")

# Combine island and P4 submerged:
denit_4seasons_IslandvSub <- rbind(denit_4seasons_Island, denit_submergedP4)

# Set factors:
denit_4seasons_IslandvSub$Water_column <- as.factor(denit_4seasons_IslandvSub$Water_column)

# Wilcox Test, nicer format, can use to verify stats on plot:
DEA_wilcox_IslandvSub<- compare_means(Denitrification_rate~Water_column, denit_4seasons_IslandvSub, group.by="Season", method = "wilcox.test", paired = T)

# Turn into data frame:
DEA_wilcox_IslandvSub <- as.data.frame(DEA_wilcox_IslandvSub)

# Export the data frame to a .csv file
#write.csv(CH4_wilcox, file = "../figures/pub/tables/Wilcox_NPvP/CH4_wilcox.csv", row.names = T)
```

```{r Four Seasons facet}
# Plot Winter and Spring together, using facet:
plot.denit_ACET_4Seasons <- ggplot(denit_combined_4Seasons, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  facet_wrap(vars(Season))+
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nRegenerative Stormwater Conveyance (RSC) Type", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center",size = 10, hide.ns = T)
  
 
plot.denit_ACET_4Seasons

#ggsave("../figures/denit_4Seasons_4Panel.png", plot=plot.denit_ACET_4Seasons, device="png", path=NULL, scale=1, width=12, height=10, dpi=600, limitsize=TRUE, bg="white")
```


```{r Legend plot}
# Create custom legend, then remove legend from above, then add legend again using ggpubr, or just in powerpoint

plot.denit_ACET_legend_mods <- ggplot(denit_ACET_WINTER, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=Up_or_down, color=Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25), labels = c("upstream", "downstream"), name = "Sample Location")+
  #scale_fill_manual(values = c("white", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Stuff")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_legend_mods
```

```{r Legend plot bottom}
plot.denit_ACET_legend_mods2 <- ggplot(denit_ACET_WINTER, aes(x=RSC, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=Up_or_down, color=Water_column), size = 5, position = position_jitterdodge()) +
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25), labels = c("upstream", "downstream"), name = "Sample Location")+
  #scale_fill_manual(values = c("white", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Stuff")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="bottom", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "RSC", y = expression(paste("ng N"[2],"O g"^{-1}," DM hr"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.denit_ACET_legend_mods2
```


```{r Legend extraction}
leg <- get_legend(plot.denit_ACET_legend_mods, position = "right") #Extract legend as a legend Grob
legend_plot <- as_ggplot(leg) #Asign the grob as a ggplot
legend_plot #View the plot

#ggsave("../figures/Legend.png", plot=legend_plot, device="png", path=NULL, scale=1, dpi=300, limitsize=TRUE, bg="white")

leg_bottom <- get_legend(plot.denit_ACET_legend_mods2, position = "bottom") #Extract legend as a legend Grob
legend_plot_bottom <- as_ggplot(leg_bottom) #Asign the grob as a ggplot
legend_plot_bottom #View the plot

#ggsave("../figures/Legend_bottom.png", plot=legend_plot_bottom, device="png", path=NULL, scale=1, dpi=600, height = 3, width = 12, limitsize=T, bg="white")

```

## Spring 2023 GEOL YSI data:

```{r}
nitrate_plot <- ggplot(YSI_data, aes(x=Date_Time, y=Nitrate_.NO3.N.mg.l.)) +
                     geom_point(aes(color=Site_Name), size = 5, position = position_jitterdodge()) +
  #scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  #scale_shape_manual(values = c(24, 25), labels = c("upstream", "downstream"), name = "Sample Location")+
  #scale_fill_manual(values = c("white", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Stuff")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Date", y = expression(paste("NO"[3]^{"-"},"-N (mg/l)")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))

nitrate_plot
```

```{r}
# Repeat above, but now with only Pool 1 and Pool 4:
YSI_data_P1P4 <- dplyr::filter(YSI_data, YSI_data$Site_Name == c("Pool 1", "Pool 4"), .preserve = TRUE)
# Above is missing two time points, so trying again with brute force approach:
YSI_data_P1P4_2 <- YSI_data[c(1, 4, 6, 9, 11, 14, 17, 20, 22, 25),]
```


```{r}
# trying to shorten the dates:

require("stringr")

ShortDates <- as.data.frame(str_split_fixed(YSI_data$Date_Time, "2023-", n = 2))
#Get rid of empty column:

colnames(ShortDates) <- c("Empty", "Short_Date")

YSI_data_2 <- cbind(YSI_data, ShortDates)

# Get rid of 'Empty' column:
YSI_data_2 <- YSI_data_2[,-19]

# Make another P1 P4 dataframe with short dates:
YSI_data_2_P1P4_2 <- YSI_data_2[c(1, 4, 6, 9, 11, 14, 17, 20, 22, 25),]
```

```{r}
nitrate_plot_P1P4 <- ggplot(YSI_data_2_P1P4_2, aes(x=Short_Date, y=Nitrate_.NO3.N.mg.l.)) +
                     geom_point(aes(color=Site_Name), size = 5, position = position_jitterdodge()) +
  #scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  #scale_shape_manual(values = c(24, 25), labels = c("upstream", "downstream"), name = "Sample Location")+
  #scale_fill_manual(values = c("white", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Stuff")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Date", y = expression(paste("NO"[3]^{"-"},"-N (mg/l)")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))

nitrate_plot_P1P4

#ggsave("../figures/YSI_nitrate.png", plot=nitrate_plot_P1P4, device="png", path=NULL, scale=1, width=10, height=7, dpi=300, limitsize=TRUE, bg="white")
```

```{r}
DO_plot_P1P4 <- ggplot(YSI_data_2_P1P4_2, aes(x=Short_Date, y=Dissolved_Oxygen_...)) +
                     geom_point(aes(color=Site_Name), size = 5, position = position_jitterdodge()) +
  #scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  #scale_shape_manual(values = c(24, 25), labels = c("upstream", "downstream"), name = "Sample Location")+
  #scale_fill_manual(values = c("white", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Stuff")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=14,face="bold"),
          axis.text=element_text(size=14),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 14), legend.position="right", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Date", y = "%DO", title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))

DO_plot_P1P4

#ggsave("../figures/YSI_DO.png", plot=DO_plot_P1P4, device="png", path=NULL, scale=1, width=10, height=7, dpi=300, limitsize=TRUE, bg="white")
```

## Sediment N data

```{r Wrangling sediment N data}
# Remove NA rows at bottom
sediment_N <- sediment_N[1:40,]

# Convert negatives into zeroes:
sediment_N_dropNegs <- sediment_N # copy into a new df to avoid overwriting original data

sediment_N_dropNegs <- sediment_N_dropNegs %>%
  dplyr::mutate(NO3.NO2_uM = ifelse(NO3.NO2_uM < 0, 0, NO3.NO2_uM))

sediment_N_dropNegs <- sediment_N_dropNegs %>%
  dplyr::mutate(NO3.NO2_mg.L = ifelse(NO3.NO2_mg.L < 0, 0, NO3.NO2_mg.L))

# Add a date column:
sediment_N_dropNegs$Season <- denit_combined_wSUMMER$Season[9:48]
sediment_N_dropNegs$RSC <- denit_combined_wSUMMER$RSC[9:48]
sediment_N_dropNegs$Pool <- denit_combined_wSUMMER$Pool[9:48]
sediment_N_dropNegs$Up_or_down <- denit_combined_wSUMMER$Up_or_down[9:48]
sediment_N_dropNegs$Water_column <- denit_combined_wSUMMER$Water_column[9:48]
sediment_N_dropNegs$combined_pool_name <- denit_combined_wSUMMER$combined_pool_name[9:48]
sediment_N_dropNegs$SampleID_DEA <- denit_combined_wSUMMER$Sample_ID[9:48]
```

```{r Plot sediment NH4 data}
# Plot Winter and Spring NH4 together, using facet:
plot.sediment_NH4 <- ggplot(sediment_N_dropNegs, aes(x=RSC, y=NH4_mg.L)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  facet_wrap(vars(Season))+
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40),axis.title=element_text(size=30,face="bold"),
          axis.text=element_text(size=30),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="none", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("NH"[4], ""^{"+"}," (mg * L"^{-1}, ")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center", size = 10, hide.ns = T)
  
 
plot.sediment_NH4
```

```{r Plot sediment NO2/NO3 data}
# Plot Winter and Spring NO2/NO3 together, using facet:
plot.sediment_NOX <- ggplot(sediment_N_dropNegs, aes(x=RSC, y=NO3.NO2_mg.L)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  facet_wrap(vars(Season))+
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=40), axis.title=element_text(size=30,face="bold"),
          axis.text=element_text(size=30),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 40), legend.position="none", legend.title = element_text(size=40), legend.text=element_text(size=40)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nRegenerative Stormwater Conveyance (RSC) Type", y = expression(paste("NO"[2], ""^{"-"},"/NO"[3], ""^{"-"}, " (mg * L"^{-1}, ")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center",size = 10, hide.ns = T)
  
 
plot.sediment_NOX
```

```{r Panel together sediment N figures}
#plot.NH4_and_NOX <- ggarrange(plot.sediment_NH4, plot.sediment_NOX, ncol = 1, nrow = 2, labels = NULL, legend.grob = leg, legend = "right")

plot.NH4_and_NOX <- ggarrange(plot.sediment_NH4, plot.sediment_NOX, ncol = 1, nrow = 2, labels = NULL, legend.grob = leg_bottom,legend = "bottom")

plot.NH4_and_NOX

#ggsave("../figures/sedimentNH4_and_NOX.png", plot=plot.NH4_and_NOX, device="png", path=NULL, scale=1, width=17, height=12, dpi=600, limitsize=TRUE, bg="white")
```


## Sediment N per dry mass

```{r Wrangling sediment N data}
# Convert negatives into zeroes:
sediment_N_DM_dropNegs <- sediment_N_DM # copy into a new df to avoid overwriting original data

sediment_N_DM_dropNegs <- sediment_N_DM_dropNegs %>%
  dplyr::mutate(nitrate..ug.NOx.g.soil. = ifelse(NO3.NO2_uM < 0, 0, nitrate..ug.NOx.g.soil.))

# Add a date column:
sediment_N_DM_dropNegs$Season <- denit_combined_wSUMMER$Season[9:48]

# Add combined pool name:
sediment_N_DM_dropNegs$combined_pool_name <- denit_combined_wSUMMER$combined_pool_name[9:48]
```

```{r stats assumptions}
# Outliers:
Outliers_Sediment_NH4 <- sediment_N_DM_dropNegs %>%
  group_by(Season) %>%
  identify_outliers(ammonia..ug.NH4.g.soil.)
  # There are extreme outliers. Could run with and without outliers.

Outliers_Sediment_NOX <- sediment_N_DM_dropNegs %>%
  group_by(Season) %>%
  identify_outliers(nitrate..ug.NOx.g.soil.)
  # There are extreme outliers. Could run with and without outliers.

# Normality:
# NH4
sediment_N_DM_dropNegs %>%
  group_by(Season) %>%
  shapiro_test(ammonia..ug.NH4.g.soil.)
  # Not normally distributed

  # QQ plot:
ggqqplot(sediment_N_DM_dropNegs, "ammonia..ug.NH4.g.soil.", facet.by = "Season")

# NOX
sediment_N_DM_dropNegs %>%
  group_by(Season) %>%
  shapiro_test(nitrate..ug.NOx.g.soil.)
  # Not normally distributed

  # QQ plot:
ggqqplot(sediment_N_DM_dropNegs, "nitrate..ug.NOx.g.soil.", facet.by = "Season")
```

```{r Wilcox test: RSC}
# Set factors:
sediment_N_DM_dropNegs$RSC <- as.factor(sediment_N_DM_dropNegs$RSC)

# Wilcox Test, nicer format, can use to verify stats on plot:
NH4_wilcox_RSC<- compare_means(ammonia..ug.NH4.g.soil.~RSC, sediment_N_DM_dropNegs, group.by="Season", method = "wilcox.test", paired = F)

# Turn into data frame:
NH4_wilcox_RSC <- as.data.frame(NH4_wilcox_RSC)

# Wilcox Test, nicer format, can use to verify stats on plot:
NOX_wilcox_RSC<- compare_means(nitrate..ug.NOx.g.soil.~RSC, sediment_N_DM_dropNegs, group.by="Season", method = "wilcox.test", paired = F)

# Turn into data frame:
NOX_wilcox_RSC <- as.data.frame(NOX_wilcox_RSC)

# Export the data frame to a .csv file
#write.csv(CH4_wilcox, file = "../figures/pub/tables/Wilcox_NPvP/CH4_wilcox.csv", row.names = T)
```

```{r Wilcox test: Upstream vs. downstream}
# Set factors:
sediment_N_DM_dropNegs$Up_or_down <- as.factor(sediment_N_DM_dropNegs$Up_or_down)

# Separate IS and dry:
sediment_N_DM_dropNegs_IS <- sediment_N_DM_dropNegs %>%
  filter(RSC == "in-stream" & Water_column == "submerged")

sediment_N_DM_dropNegs_Dry <- sediment_N_DM_dropNegs %>%
  filter(RSC == "dry")

# Wilcox Test, nicer format, can use to verify stats on plot:
NH4_wilcox_UpvsDown_IS<- compare_means(ammonia..ug.NH4.g.soil.~Up_or_down, sediment_N_DM_dropNegs_IS, group.by="Season", method = "wilcox.test", paired = T)

# Turn into data frame:
NH4_wilcox_UpvsDown_IS <- as.data.frame(NH4_wilcox_UpvsDown_IS)

# Wilcox Test, NH4 dry:
NH4_wilcox_UpvsDown_Dry<- compare_means(ammonia..ug.NH4.g.soil.~Up_or_down, sediment_N_DM_dropNegs_Dry, group.by="Season", method = "wilcox.test", paired = T)

# Turn into data frame:
NH4_wilcox_UpvsDown_Dry <- as.data.frame(NH4_wilcox_UpvsDown_Dry)

# Wilcox Test, NOX In-stream:
NOX_wilcox_UpvsDown_IS<- compare_means(nitrate..ug.NOx.g.soil.~Up_or_down, sediment_N_DM_dropNegs_IS, group.by="Season", method = "wilcox.test", paired = T)

# Turn into data frame:
NOX_wilcox_UpvsDown_IS <- as.data.frame(NOX_wilcox_UpvsDown_IS)

# Wilcox Test, NOX dry:
NOX_wilcox_UpvsDown_Dry<- compare_means(nitrate..ug.NOx.g.soil.~Up_or_down, sediment_N_DM_dropNegs_Dry, group.by="Season", method = "wilcox.test", paired = T)

# Turn into data frame:
NOX_wilcox_UpvsDown_Dry <- as.data.frame(NOX_wilcox_UpvsDown_Dry)

# Export the data frame to a .csv file
#write.csv(CH4_wilcox, file = "../figures/pub/tables/Wilcox_NPvP/CH4_wilcox.csv", row.names = T)
```


```{r Plot sediment NH4 data}
# Plot Winter and Spring NH4 together, using facet:
plot.sediment_NH4_DM <- ggplot(sediment_N_DM_dropNegs, aes(x=RSC, y=ammonia..ug.NH4.g.soil.)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  facet_wrap(vars(Season))+
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µg NH"[4], ""^{"+"}," g"^{-1}, " DM")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center", size = 10, hide.ns = T)
  
 
plot.sediment_NH4_DM
```

```{r Plot sediment NO2/NO3 data}
# Plot Winter and Spring NO2/NO3 together, using facet:
plot.sediment_NOX_DM <- ggplot(sediment_N_DM_dropNegs, aes(x=RSC, y=nitrate..ug.NOx.g.soil.)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  facet_wrap(vars(Season))+
  scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
  scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20), axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nRegenerative Stormwater Conveyance (RSC) Type", y = expression(paste("µg NO"["x"], ""^{"-"},"  g"^{-1}, " DM")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center",size = 10, hide.ns = T)
  
 
plot.sediment_NOX_DM
```

```{r Panel together sediment N figures}
plot.NH4_and_NOX_DM <- ggarrange(plot.sediment_NH4_DM, plot.sediment_NOX_DM, ncol = 1, nrow = 2, labels = NULL, legend = "none")

plot.NH4_and_NOX_DM

#ggsave("../figures/SedimentN_4Panel.png", plot=plot.NH4_and_NOX_DM, device="png", path=NULL, scale=1, width=12, height=10, dpi=600, limitsize=TRUE, bg="white")
```


## Precipitation

```{r Testing USGS precipitation data}
install.packages("dataRetrieval")
library("dataRetrieval")

siteNumber <- "02084000"
parameterCd <- "00045"

SpringPrecip <- readNWISdv(
  siteNumber, parameterCd,
  "2023-03-22", "2023-03-29", statCd = "00006")

SummerPrecip <- readNWISdv(
  siteNumber, parameterCd,
  "2023-06-14", "2023-06-21", statCd = "00006")

# Add Season column
SpringPrecip$Season <- "Spring (March 2023)"
SummerPrecip$Season <- "Summer (June 2023)"

# Merge:
precip_SpringSummer <- merge(SpringPrecip, SummerPrecip, all = T)

```

```{r plot USGS precip data}
plot.precip <- ggplot(precip_SpringSummer, aes(x=Date, y=X_00045_00006)) +
                     geom_line(aes(linewidth= 1), arrow = arrow(angle = 90, ends = "last", type = "closed")) +
                     #geom_point(aes(shape=combined_pool_name, color=Water_column, fill = Water_column), size = 5, position = position_jitterdodge()) +
  facet_wrap(vars(Season), scales = "free_x")+
  #scale_color_manual(values=c("#E69F00","#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level") +
  #scale_shape_manual(values = c(24, 25, 24, 25), labels = c("Dry RSC, up", "Dry RSC, down", "In-stream RSC, up", "In-stream RSC, down"), name = "Sample Location")+
 # scale_fill_manual(values = c("#E69F00", "#009E73","#56B4E9"), labels = c("dry", "island", "submerged"), name="Water Level")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=14),axis.title=element_text(size=21,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=14), legend.text=element_text(size=14)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Date", y = "Total Precipitation (inches)", title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  
 
plot.precip

ggsave("../figures/precipSprSum.png", plot=plot.precip, device="png", path=NULL, scale=1, width=16, height=7, dpi=600, limitsize=TRUE, bg="white")
```



## Pre- and post-RSC

```{r set factors and names}
# set restoration levels:
denit_PRE_POST$restoration <- denit_PRE_POST$restoration %>% factor(levels = c("PRE", "POST"))

# Change water_column names to better labels:
denit_PRE_POST$Water_column_Label <- denit_PRE_POST$Water_column %>% str_replace_all(c("W" = "water \n(PRE)", "BK" = "streambank \n(PRE)", "BD" = "streambed \n(PRE)", "dry" = "dry \n(POST)", "island" = "streambank \n(POST)", "submerged" = "streambed \n(POST)"))

# set Water_column_Label factor levels:
denit_PRE_POST$Water_column_Label <- denit_PRE_POST$Water_column_Label %>% factor(levels = c("water \n(PRE)", "streambank \n(PRE)", "streambed \n(PRE)", "dry \n(POST)", "streambank \n(POST)", "streambed \n(POST)"))
```


```{r Plotting pre and post RSC DEA}
plot.denit_PRE_POST <- ggplot(denit_PRE_POST, aes(x=Water_column_Label, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(color=Water_column_Label, shape=restoration), size = 4, position = position_jitterdodge()) +
  scale_color_manual(values=c("#0072B2","#009E73","#D55E00", "#E69F00", "#009E73", "#D55E00"), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="") +
  scale_shape_manual(values = c(16,17), labels = c("Pre-restoration", "Post-restoration"), name="")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nSample Type", y = expression(paste("Denitrification (ng N"[2],"O (g DM)"^-{1}," hr"^-{1},")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
  #stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center",size = 10, hide.ns = T)
  
 
plot.denit_PRE_POST
```
```{r create and extract legend}
plot.denit_PRE_POST_LEG <- ggplot(denit_PRE_POST, aes(x=Water_column_Label, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(color=Water_column_Label, shape=Water_column_Label), size = 4, position = position_jitterdodge()) +
  scale_color_manual(values=c("#0072B2","#009E73","#D55E00", "#E69F00", "#009E73", "#D55E00"), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend") +
  scale_shape_manual(values = c(16,16,16,17,17,17), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nSample Type", y = expression(paste("Denitrification (ng N"[2],"O (g DM)"^-{1}," hr"^-{1},")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))
 
plot.denit_PRE_POST_LEG
```
### Pre and post RSC stats

```{r ANOVAS prep}
# https://www.datanovia.com/en/lessons/repeated-measures-anova-in-r/

# Make sure factors are factors 
```

```{r ANOVA assumption testing: outliers}
Outliers_PrePost <- denit_PRE_POST %>%
  identify_outliers(Denitrification_rate)
  # There are extreme outliers.
```
  
```{r ANOVA assumption testing: normality}
denit_PRE_POST %>%
  shapiro_test(Denitrification_rate)
  # Not normally distributed

  # QQ plot:
ggqqplot(denit_PRE_POST, "Denitrification_rate")

# log transform:
denit_PRE_POST$log_Denit <- log10(denit_PRE_POST$Denitrification_rate)

denit_PRE_POST %>%
  shapiro_test(log_Denit)
  # Not normally distributed

  # QQ plot:
ggqqplot(denit_PRE_POST, "log_Denit")

# log transformed data looks almost acceptable for parametric stats, but will use nonparametric approach for now, especially given unbalanced design
```

```{r Wilcoxon Rank Sum for PRE vs POST}
wilcox_PrePost <- wilcox.test(data = denit_PRE_POST, Denitrification_rate ~ restoration, paired = F)
wilcox_PrePost

# post is significantly different from pre
```

```{r Kruskal-Wallis}
# Will use DWASS-Steel-Critchlow-Fligner test for multiple comparisons, in package NSM3

# Kruskal for overall differences:
kruskal_DEA <- kruskal.test(data = denit_PRE_POST, Denitrification_rate ~ Water_column_Label)
kruskal_DEA


# Pairwise comparisons:
SDCFlig_DEA<- pSDCFlig(x = denit_PRE_POST$Denitrification_rate, g = denit_PRE_POST$Water_column_Label, method = "Monte Carlo", n.mc = 10000)
SDCFlig_DEA
```

```{r stats prep for plotting}
# Kruskal-Wallis test on Water_column, and multiple comparisons:
kruskal_DF_compMeans <- compare_means(Denitrification_rate~Water_column_Label, denit_PRE_POST, method = "kruskal.test")

kruskal_DF_multComparisons <- compare_means(Denitrification_rate~Water_column_Label, denit_PRE_POST, method = "wilcox.test", p.adjust.method = "fdr")

# Adjustments for plotting:
kruskal_DF_multComparisons <- add_significance(kruskal_DF_multComparisons, p.col = "p.adj", output.col = "p.adj.signif", cutpoints = c(0, 1e-04, 0.001, 0.01, 0.05, Inf), symbols = c("****", "***", "**", "*", "ns"))

# Turn into data frame:
kruskal_DF_multComparisons <- as.data.frame(kruskal_DF_multComparisons)

# Add on SDCFlig p-values:
kruskal_DF_multComparisons$SDCF_p <- SDCFlig_DEA$p.val

# Symbols for plotting:
kruskal_DF_multComparisons <- add_significance(kruskal_DF_multComparisons, p.col = "SDCF_p", output.col = "p.SDCF.signif", cutpoints = c(0, 1e-04, 0.001, 0.01, 0.05, Inf), symbols = c("****", "***", "**", "*", "ns"))

# Export the data frames to a .csv file
#write.csv(CH4_MultComp.DF, file = "../figures/pub/tables/Kruskal_Treatment/multiple_comparisons/CH4_MultComp.csv", row.names = T)

# try reduced data frame so as not to confuse stat_pval_manual:
SDCFlig_Manual_DF <- kruskal_DF_multComparisons %>% dplyr::select(c(".y.", "group1", "group2", "SDCF_p", "p.SDCF.signif"))

# rename columns to match stat_pval:
colnames(SDCFlig_Manual_DF) <- c(".y.", "group1", "group2", "p", "p.signif")
```

```{r Plot with pairwise comparisons}
plot.denit_PRE_POST_stats <- ggplot(denit_PRE_POST, aes(x=Water_column_Label, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(color=Water_column_Label, shape=Water_column_Label), size = 4, position = position_jitterdodge()) +
  scale_color_manual(values=c("#0072B2","#009E73","#D55E00", "#E69F00", "#009E73", "#D55E00"), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend") +
  scale_shape_manual(values = c(16,16,16,17,17,17), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nSample Type", y = expression(paste("Denitrification (ng N"[2],"O (g DM)"^-{1}," hr"^-{1},")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_pvalue_manual(data = SDCFlig_Manual_DF, label = "p.signif", size = 10, vjust = 1, hide.ns = T, y.position = (max(denit_PRE_POST$Denitrification_rate)), step.increase = 0.1)
 
plot.denit_PRE_POST_stats
```

```{r Plot with Wilcox, pre vs. post}
plot.denit_PRE_POST_Wilcox <- ggplot(denit_PRE_POST, aes(x=restoration, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(shape=restoration), size = 4, position = position_jitterdodge()) +
  #scale_color_manual(values=c("#0072B2","#009E73","#D55E00", "#E69F00", "#009E73", "#D55E00"), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend") +
  scale_shape_manual(values = c(16,17), labels = c("Pre-restoration","Post-restoration"), name="Legend")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("Denitrification (ng N"[2],"O (g DM)"^-{1}," hr"^-{1},")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))+
  stat_compare_means(method = "wilcox.test", paired = F, label = "p.signif", label.y.npc = "center", label.x.npc = "center", size = 10, hide.ns = T)
 
plot.denit_PRE_POST_Wilcox
```

```{r}
# make multcomp figure using letter symbols (A, AB, B, etc.)

require("PMCMRplus")

DSCF_PMCRMR <- dscfAllPairsTest(x = denit_PRE_POST$Denitrification_rate, g = denit_PRE_POST$Water_column_Label)
DSCF_PMCRMR

PMCMRplus::barPlot(DSCF_PMCRMR)


# Add to df:
denit_PRE_POST$cld <- denit_PRE_POST$Water_column %>% str_replace_all(c("W" = "a", "BK" = "b", "BD" = "b", "dry" = "b", "island" = "c", "submerged" = "c"))
```

```{r}
plot.denit_PRE_POST_stats2 <- ggplot(denit_PRE_POST, aes(x=Water_column_Label, y=Denitrification_rate)) +
                     geom_boxplot(outlier.shape = NA) +
                     geom_point(aes(color=Water_column_Label, shape=Water_column_Label), size = 4, position = position_jitterdodge()) +
  geom_text(data = denit_PRE_POST, aes(x=Water_column_Label, y=(max(Denitrification_rate)+200)), label = denit_PRE_POST$cld, size = 7)+
  scale_color_manual(values=c("#0072B2","#009E73","#D55E00", "#E69F00", "#009E73", "#D55E00"), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend") +
  scale_shape_manual(values = c(16,16,16,17,17,17), labels = c("water (PRE)", "streambank (PRE)", "streambed (PRE)", "dry (POST)", "streambank (POST)", "streambed (POST)"), name="Legend")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="right", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "\nSample Type", y = expression(paste("Denitrification (ng N"[2],"O (g DM)"^-{1}," hr"^-{1},")")), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA))

 
plot.denit_PRE_POST_stats2
```

